-libraryjars /home/pankaj/WTK2.5.2/lib/midpapi10.jar:/home/pankaj/WTK2.5.2/lib/cldcapi10.jar:/home/pankaj/WTK2.5.2/lib/cldcapi10.jar
-injars /home/pankaj/j2mewtk/2.5.2/apps/Expense_Tracker/bin/Expense_Tracker.jar
-outjar /tmp/Expense_Tracker.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
